var dir_1b11991530aa07e314ae128c01f71e88 =
[
    [ "hri_adc_g55.h", "hri__adc__g55_8h.html", null ],
    [ "hri_chipid_g55.h", "hri__chipid__g55_8h.html", null ],
    [ "hri_cmcc_g55.h", "hri__cmcc__g55_8h.html", null ],
    [ "hri_crccu_g55.h", "hri__crccu__g55_8h.html", null ],
    [ "hri_efc_g55.h", "hri__efc__g55_8h.html", null ],
    [ "hri_flexcom_g55.h", "hri__flexcom__g55_8h.html", null ],
    [ "hri_g55.h", "hri__g55_8h.html", null ],
    [ "hri_gpbr_g55.h", "hri__gpbr__g55_8h.html", null ],
    [ "hri_i2sc_g55.h", "hri__i2sc__g55_8h.html", null ],
    [ "hri_lockbit_g55.h", "hri__lockbit__g55_8h.html", null ],
    [ "hri_matrix_g55.h", "hri__matrix__g55_8h.html", null ],
    [ "hri_mem2mem_g55.h", "hri__mem2mem__g55_8h.html", null ],
    [ "hri_mpu_g55.h", "hri__mpu__g55_8h.html", null ],
    [ "hri_nvic_g55.h", "hri__nvic__g55_8h.html", null ],
    [ "hri_pdc_g55.h", "hri__pdc__g55_8h.html", null ],
    [ "hri_pdmic_g55.h", "hri__pdmic__g55_8h.html", null ],
    [ "hri_pio_g55.h", "hri__pio__g55_8h.html", null ],
    [ "hri_pmc_g55.h", "hri__pmc__g55_8h.html", null ],
    [ "hri_rstc_g55.h", "hri__rstc__g55_8h.html", null ],
    [ "hri_rtc_g55.h", "hri__rtc__g55_8h.html", null ],
    [ "hri_rtt_g55.h", "hri__rtt__g55_8h.html", null ],
    [ "hri_spi_g55.h", "hri__spi__g55_8h.html", null ],
    [ "hri_supc_g55.h", "hri__supc__g55_8h.html", null ],
    [ "hri_systemcontrol_g55.h", "hri__systemcontrol__g55_8h.html", null ],
    [ "hri_systick_g55.h", "hri__systick__g55_8h.html", null ],
    [ "hri_tc_g55.h", "hri__tc__g55_8h.html", null ],
    [ "hri_twi_g55.h", "hri__twi__g55_8h.html", null ],
    [ "hri_udp_g55.h", "hri__udp__g55_8h.html", null ],
    [ "hri_uhp_g55.h", "hri__uhp__g55_8h.html", null ],
    [ "hri_usart_g55.h", "hri__usart__g55_8h.html", null ],
    [ "hri_wdt_g55.h", "hri__wdt__g55_8h.html", null ]
];